### ISSUE TITLE
Inconsistant `end_datetime`

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/noaa-climate-normals#4]
- Start of day: https://github.com/stactools-packages/noaa-climate-normals/blob/b9ed6477110761bbcb3d57212149ae2e302aa31d/src/stactools/noaa_climate_normals/netcdf/stac.py#L54
- Start of day: https://github.com/stactools-packages/noaa-climate-normals/blob/b9ed6477110761bbcb3d57212149ae2e302aa31d/src/stactools/noaa_climate_normals/gridded/stac.py#L83
- End of day: https://github.com/stactools-packages/noaa-climate-normals/blob/b9ed6477110761bbcb3d57212149ae2e302aa31d/src/stactools/noaa_climate_normals/tabular/stac.py#L78

I _think_ these should all be end of day?

**Comment by gadomski** [comment]
Same for all three temporal extents, e.g. https://github.com/stactools-packages/noaa-climate-normals/blob/b9ed6477110761bbcb3d57212149ae2e302aa31d/src/stactools/noaa_climate_normals/gridded/constants.py#L65.

**Comment by pjhartzell** [comment]
Yeah, good catch. Fixing.

**Comment by pjhartzell** [comment]
fixed.
