### ISSUE TITLE
`derived_from` should only link to STAC items

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/noaa-climate-normals#5]
From [the spec](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#relation-types):

> derived_from: URL to a STAC Item that was used as input data in the creation of this Item.

I found one incorrect usage:

https://github.com/stactools-packages/noaa-climate-normals/blob/b9ed6477110761bbcb3d57212149ae2e302aa31d/src/stactools/noaa_climate_normals/gridded/stac.py#L100

**Comment by pjhartzell** [comment]
That link is to a STAC Item. Example: https://github.com/stactools-packages/noaa-climate-normals/blob/b9ed6477110761bbcb3d57212149ae2e302aa31d/examples/noaa-climate-normals-gridded/2006_2020-daily-1/2006_2020-daily-1.json#L58

Or am I missing the point?

**Comment by gadomski** [comment]
Nope, you're right...I misread the code.
